<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>mc</string>
   </array>
  <key>name</key>
  <string>dps6</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.mc</string>
  <key>uuid</key>
  <string>9b75d58e-dc00-4d67-8b1c-00eb9f8d269b</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(lsc[1-7]|tc[0-9][0-9])</string>
          <key>name</key>
          <string>variable.function.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(rsc[1-7])</string>
          <key>name</key>
          <string>punctuation.definition.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(uop)</string>
          <key>name</key>
          <string>constant.language.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.text|(.global.*$))</string>
          <key>name</key>
          <string>variable.parameter.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((&lt;)(\w+$))</string>
          <key>name</key>
          <string>variable.parameter.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((~0x.*$))</string>
          <key>name</key>
          <string>constant.numeric.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\w+)(:$))</string>
          <key>name</key>
          <string>variable.parameter.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(gp[0-9a-f]+)</string>
          <key>name</key>
          <string>support.constant.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(bib|dia|dic|rfu|din|bir|diw|di_dir)</string>
          <key>name</key>
          <string>keyword.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(afadd|afk_1|afj_1|afior|afknj|afxor|afxnr|afinc|afk_j|afj_k|amior|afand|amknj|amxor|amxnr)</string>
          <key>name</key>
          <string>punctuation.definition.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(adfq|adfn|adlr|adfr|addr|adsr|addl|adsl)</string>
          <key>name</key>
          <string>keyword.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(brtct|catct|xat|xbt|rttct|xwt|xet|xft|brtcf|catcf|xaf|xbf|rttcf|xwf|xef|xff)</string>
          <key>name</key>
          <string>punctuation.definition.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(pmus|purg|ymux|yinc|ylod|pinc|pagj|ygjw|ybay|plod|yrel|yold|drcl|drcb|drci|iorc|dwhw|dwwu|dwhl|dwwl|iowu|iowh|ioww|prci|dsty|dshy|dstu|pnop|dshp|dstl|dshl|prcp|psty|pshy|pstl|psti|pshl|dshu)</string>
          <key>name</key>
          <string>keyword.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(k_0|k_1|k_2|k_3|k_4|k_5|k_6|k_7|k_8|k_9|k_a|k_b|k_c|k_d|k_e|k_f|k0yz|kfyz)</string>
          <key>name</key>
          <string>constant.language.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(awlq|awlr|awzq|awzr|awzl|awil|awiq|awiz|aslq|aslr|aszq|aszr|aszl|asil|asiq|asiz)</string>
          <key>name</key>
          <string>constant.language.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(bir|bits|bil|dstx|bia|dshx|bib|biv|pstx|bitc|bih|biz|pshx|bix|bii|bis|binop|ri1|ri2|ri3|ri4|ri5|ri6|ri7|ri8|ri9|ria|rib|ric|rid|rie|rif)</string>
          <key>name</key>
          <string>variable.function.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(smn|smx|sme|smnu|smd|smr|sms)</string>
          <key>name</key>
          <string>keyword.operator.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\s?\w+$))</string>
          <key>name</key>
          <string>keyword.dps6</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.dps6</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.dps6</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dps6</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.dps6</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.dps6</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.dps6</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.dps6</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.dps6</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.dps6</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.dps6</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>

